### ISSUE TITLE
Unable to install Selenium? 

### ISSUE THREAD

**Issue by Elddreki2** [hevalhazalkurt/PinPy#4]
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip3 install selenium
  File "<stdin>", line 1
    pip3 install selenium
         ^
SyntaxError: invalid syntax
>>>

Im on windows 10 64bit. Just installed Python... I really want to use this, but I need help

**Comment by Elddreki2** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pip' is not defined
>>> pip version
  File "<stdin>", line 1
    pip version
        ^
SyntaxError: invalid syntax
>>> $pip
  File "<stdin>", line 1
    $pip
    ^
SyntaxError: invalid syntax
>>>
>>> $ pip
  File "<stdin>", line 1
    $ pip
    ^
SyntaxError: invalid syntax
>>> pip3 install selenium
  File "<stdin>", line 1
    pip3 install selenium
         ^
SyntaxError: invalid syntax
>>> pip install selenium
  File "<stdin>", line 1
    pip install selenium
        ^
SyntaxError: invalid syntax
>>> pip install -U selenium
  File "<stdin>", line 1
    pip install -U selenium
        ^
SyntaxError: invalid syntax
>>> python setup.py install
  File "<stdin>", line 1
    python setup.py install
           ^
SyntaxError: invalid syntax
>>>



I've literally tried every up to date code....

**Comment by hevalhazalkurt** [comment]
Working on a Windows system can be different. First, you need to install `pip` in your system. As I can see you don't have `pip` on your system yet. So you can install `pip` first (check : https://pip.pypa.io/en/stable/installing/) then install PinPy, or you can download Selenium directly on the Selenium webpage (check : https://www.selenium.dev).

**Comment by Elddreki2** [comment]
> Working on a Windows system can be different. First, you need to install `pip` in your system. As I can see you don't have `pip` on your system yet. So you can install `pip` first (check : https://pip.pypa.io/en/stable/installing/) then install PinPy, or you can download Selenium directly on the Selenium webpage (check : https://www.selenium.dev).

I've tried directly downloading Selenium from their website. I'm feeling really stupid right now lol... Thanks for the reply. Alright, so let's see, I am going to need a lot of help if that is not a problem from your end.. I'm handy with Java and JavaScript but not running Python... 
I went to the first website you sent (https://pip.pypa.io/en/stable/installing/), and followed the WINDOWS instructions (There's two, I made sure to click the Windows selection). I would first like to say I am running these commands on C:\Windows\py.exe
The first command is:
C:\> py -m pip --version
pip X.Y.Z from ...\site-packages\pip (python X.Y)

-- I tried running them individually and at once. This is what I got.

>>> pip X.Y.Z from ...\site-packages\pip (python X.Y)
  File "<stdin>", line 1
    pip X.Y.Z from ...\site-packages\pip (python X.Y)
        ^
SyntaxError: invalid syntax

-- That was both ran at once. Ran individually...

>>> C:\> py -m pip --version
  File "<stdin>", line 1
SyntaxError: unexpected character after line continuation character

>>> pip X.Y.Z from ...\site-packages\pip (python X.Y)
  File "<stdin>", line 1
    pip X.Y.Z from ...\site-packages\pip (python X.Y)
        ^
SyntaxError: invalid syntax

-- Maybe I should be running these on command prompt? I tried doing so, and got: 

C:\WINDOWS\system32>pip X.Y.Z from ...\site-packages\pip (python X.Y)
ERROR: unknown command "X.Y.Z"

-- Well.... Anyways... I ran the next command to actually INSTALL PIP (Bookmark https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py) And it successfully worked! I got:

C:\WINDOWS\system32>curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1842k  100 1842k    0     0  1842k      0  0:00:01  0:00:01 --:--:-- 1759k

So that's installed, obviously. Let's see what's next. So I figured I am going to have to switch back and forth between CMD and PY. I ran the next command and got this..

Command: py get-pip.py
Result: C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Collecting pip
  Downloading pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 2.2 MB/s
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-20.3.3 wheel-0.36.2

Nice.
From continuing to read, I've found out about Setuptools and Wheel. Wheel was just installed, but it warned me Setup tools wasn't. I can't find where setuptools are. First question - Do I need setuptools?
I am running Python 3.9. The website says it's compatible with "CPython versions 2.7, 3.5, 3.6, 3.7, 3.8 and also PyPy." Am I good there?
Bookmarked the page so I can find the commands for later use. (It also has an upgrade command). I will now attempt to install Selenium to run the Webdriver.
I used your command:
pip3 install selenium
in CMD, and here are the results.

Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 1.3 MB/s
Collecting urllib3
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 3.2 MB/s
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.26.2

Yay!

Next up, WebDriver. I believe I am using Chrome 88. I am unsure how to check, but I have the most recent version, which according to my quick google is Chrome 88. Let's use that. 
I just successfully installed, unzipped, and ran the Chrome 99 WebDriver.
Pin.py now has a icon in the folder. It is usually blank. I will now attempt to run it...

Okay, so when I double click Pin.py, it loads up a blank CMD-Prompt screen then closes immediately. I tried unzipping from the original folder I downloaded from here to see if Pin.py was corrupted, but it just doesn't load up. So I've successfully gotten to this point... I would really appreciate some more help. (PS, if you're reading the code, let me know if there's any important information I missed that I wouldn't want public, I looked and don't see anything).

**Comment by Elddreki2** [comment]
Ahh, I am an idiot! I was running it and wasn't editing the stuff like an idiot! I am filling in the info and following the tutorial, will reply with feedback! Dude, you realize you could sell this to people, right?

**Comment by Elddreki2** [comment]
Alrighty! I'm back! So despite filling everything out and making sure their were no typos, it still won't run. Same as before. Loads up the CMD screen, then closes. I would really appreciate some help...

**Comment by Elddreki2** [comment]
I forced it to run in the Python Idle Shell 3.9.1 and I got this:
Traceback (most recent call last):
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\horto\Desktop\PinPy-master\PinPy-master\pin.py", line 22, in <module>
    driver = webdriver.Chrome('./chromedriver')
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by Elddreki2** [comment]
![Capture](https://user-images.githubusercontent.com/77534853/105109723-17babc80-5a8b-11eb-86b0-1ad547074763.PNG)

**Comment by hevalhazalkurt** [comment]
The program can't reach the chromedriver. You need to move your chromedriver into your PinPy folder. Or you can define your path. 

Find the code on line 22. It means your chromedriver in your folder. 
`driver = webdriver.Chrome('./chromedriver')`

See the below example. It defines the path where the chromedriver as an example. 
`driver = webdriver.Chrome("C:/Users/Elddreki2/Downloads/chromedriver_win32/chromedriver.exe")`

**Comment by Elddreki2** [comment]
> The program can't reach the chromedriver. You need to move your chromedriver into your PinPy folder. Or you can define your path.
> 
> Find the code on line 22. It means your chromedriver in your folder.
> `driver = webdriver.Chrome('./chromedriver')`
> 
> See the below example. It defines the path where the chromedriver as an example.
> `driver = webdriver.Chrome("C:/Users/Elddreki2/Downloads/chromedriver_win32/chromedriver.exe")`

Ahh, I feel goofy. So I put the webdriver in the folder, same folder as the Pin.py. It loaded successfully now! The first time it didn't log me in, so I closed it. I reloaded it, and it logged me in. It went to the pin creater after logging me in. However it stopped there and did nothing.... Here is the error code. So I will debug this...

Traceback (most recent call last):
  File "C:\Users\horto\Desktop\PinPy-master\PinPy-master\pin.py", line 187, in <module>
    pin()
  File "C:\Users\horto\Desktop\PinPy-master\PinPy-master\pin.py", line 147, in pin
    driver.find_element_by_xpath(image_input).send_keys(image_file + img)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : Users\horto\Desktop\PinPy-master (1)\PinPy-master\images10_TAC Force Tactical Spring Assisted Knife 4.5.jpg
  (Session info: chrome=87.0.4280.141)

It looks like the images path is messed up. So I will fix that then try again. 
Alright I Just fixed it. It was the path to the duplicate file ( I extracted twice by mistake, so I had Pin.py (1). Ran it, logged in, went to pins, and gave this:
Traceback (most recent call last):
  File "C:\Users\horto\Desktop\PinPy-master\PinPy-master\pin.py", line 187, in <module>
    pin()
  File "C:\Users\horto\Desktop\PinPy-master\PinPy-master\pin.py", line 147, in pin
    driver.find_element_by_xpath(image_input).send_keys(image_file + img)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : Users\horto\Desktop\PinPy-master\PinPy-master\images10_TAC Force Tactical Spring Assisted Knife 4.5.jpg
  (Session info: chrome=87.0.4280.141)

Hmm.. I just found out theres a Debug file in Pin.py. Here it is.

[0120/104155.278:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
[0120/104155.281:ERROR:exception_snapshot_win.cc(99)] thread ID 9132 not found in process
[0120/104155.328:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
[0120/104155.328:ERROR:exception_snapshot_win.cc(99)] thread ID 7312 not found in process
[0120/110603.622:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
[0120/110603.624:ERROR:exception_snapshot_win.cc(99)] thread ID 4140 not found in process
[0120/110603.673:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
[0120/110603.673:ERROR:exception_snapshot_win.cc(99)] thread ID 9720 not found in process

I found out I had a typo in the images path. I failed to put a \ at the end of images. Let's run it again now. 
Okay so after correcting the path, even though I have the Webdriver in the same folder, it doesn't load. It starts the window, then closes immediately. Let's debug it and force run in IDLE shell.
It fails to start and shows a red line beside:
image_file = "Users\horto\Desktop\PinPy\images\"
It doesn't make sense. It won't accept the valid path but it's accepting the incomplete path to where it doesn't grab images (File not found : Users\horto\Desktop\PinPy-master\PinPy-master\"images10_TAC" Force Tactical Spring Assisted Knife 4.5.jpg)
Emphasis put in quotation marks. I'll try something else. Windows uses \ in their nav, but I am going to try replacing it with /.
It still won't have it... Same error.. 
Traceback (most recent call last):
  File "C:\Users\horto\Desktop\PinPy\pin.py", line 187, in <module>
    pin()
  File "C:\Users\horto\Desktop\PinPy\pin.py", line 147, in pin
    driver.find_element_by_xpath(image_input).send_keys(image_file + img)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : Users/horto/Desktop/PinPy/images/10_TAC Force Tactical Spring Assisted Knife 4.5.jpg
  (Session info: chrome=87.0.4280.141)
I just don't get it man.

**Comment by hevalhazalkurt** [comment]
Let's try a different approach :)
Please send me your PinPy folder with your jpeg and .txt files. I'll fix it and send it back to you. So you can see how you should set your image-link pairs and other things and execute your next pins. OK? You can use WeTransfer or Google Drive to share. After I'll get your folder you can delete the sharing link. Also, I don't need your Pinterest account, please delete them before sending it to me :)

**Comment by Elddreki2** [comment]
> Let's try a different approach :)
> Please send me your PinPy folder with your jpeg and .txt files. I'll fix it and send it back to you. So you can see how you should set your image-link pairs and other things and execute your next pins. OK? You can use WeTransfer or Google Drive to share. After I'll get your folder you can delete the sharing link. Also, I don't need your Pinterest account, please delete them before sending it to me :)

Thank you so much for helping. I am sorry for being so annoying lol. Here it is, I left something in there for you to read explaining the weird link format. https://drive.google.com/file/d/1IQcJKUVetr64v3MapJLXEOwEPzRRq1en/view?usp=sharing Let me know when you got it!

**Comment by Elddreki2** [comment]
Were you able to download it?

**Comment by hevalhazalkurt** [comment]
Yes, I got your files, you can delete the link.

**Comment by hevalhazalkurt** [comment]
OK, @Elddreki2 you can find your PinPy folder in your email. But I want to make something clear things for you and other people who experience the same errors. 

1. `description` : This variable is important for Pinterest marketing not for PinPy. So you need to create a description that not long, defines your products and helps other people to find them in Pinterest. 
2. wrong image sorting : Don't forget in the programming world numbers starts with 0 :) So if you sort your image by hand you need to start with 01 or 001, not with 1. You can see the image naming in your image folder. Sometimes computers can sort the image files wrong because of the special characters. So I added your codes one extra line `image_list = sorted(image_list)`  it will help you. 
3. `board_data` : PinPy didn't work on your computer because you couldn't create your boards correctly. Every board has a `keyword` section. This section very important because one of these keywords must be in the image name. That's how the program make a decision about the boards. You can see what I mean by your edited codes. 
3. image name : Every user uses different images or product names so it means sometimes the user needs to edit the function called `pre_name()`. I made a few simple edits in your code. 
4. general tags : General tags are for marketing purposes. Don't use the same tags for the board tags. Your products or pins can be in different boards but these all products can share a common keyword. For example, let's assume you have a brand named "tech bee" and you produce keyboards, t-shirts, mousepads, etc. So you can create 3 board with related tags for your product groups and add your common tags "#techbee #tech #technology #geek " in your general tags. As I said it isn't for PinPy it's for your Pinterest marketing :)

**Comment by Elddreki2** [comment]
@hevalhazalkurt Thank you very much, I am about to download it and go through the steps and look at everything! I want to thank you sooooo much!

**Comment by Elddreki2** [comment]
@hevalhazalkurt Alright, I am not going to waste anymore of your time. I appreciate you trying to help but it still doesn't work. I tried running it after _reading_ the edits you made and looking at what you changed and it still refuses to work properly. I then edited the board link name to "Knives" Since that is the board I am pinning to. That may be wrong, but the board that was there already was the coding board. I'm just so helpless lol.
# Defining your Pinterest boards, keywords, link and tags
board_data = {"knives": {
                        "keywords": ["KNIFE", "POCKET", "KNIVES"],
                        "link": "//*[@title='Knives']",
                        "tags": "#knives #knife #pocketknives #survivalknives #outdoorknives #bestknives"},
             "camping": {
                        "keywords": ["CAMP", "CAMPING", "TENT"],
                        "link": "//*[@title='Knives']",
                        "tags": "#camp #camping #outdoor #tent"},
                }

That's all I changed. I tried debugging and running it and reading the output and it still says the same thing about the image path having trouble.

`Traceback (most recent call last):
  File "C:\Users\horto\Desktop\PinPy\PinPy\pin_copy.py", line 180, in <module>
    pin()
  File "C:\Users\horto\Desktop\PinPy\PinPy\pin_copy.py", line 140, in pin
    driver.find_element_by_xpath(image_input).send_keys(image_file + img)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 477, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT,
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\horto\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : Users\horto\Desktop\PinPy\images 01_Rush_Deer_RG10_Folding_Knife_with_Liner_Lock_Pocketclip_Glass_Breaker_Seatbelt_Cutter.jpg
  (Session info: chrome=87.0.4280.141)`

I appreciate all the help... :(

**Comment by hevalhazalkurt** [comment]
First, delete the camping section it's just an example for you to understand. If you have more board you can add them later when you totally understand the program. So the section could be like this : 

```python
board_data = {"knives": {
                        "keywords": ["KNIFE", "POCKET", "KNIVES"],
                        "link": "//*[@title='Knives']",
                        "tags": "#knives #knife #pocketknives #survivalknives #outdoorknives #bestknives"}
                       }
```

Then maybe you should check your image path. If you try to run the program on your downloaded folder the path can't be as ` Users\horto\Desktop\PinPy\images `.
Look you try to run the program on `C:\Users\horto\Desktop\PinPy\PinPy\pin_copy.py` can you see the problem? There is a second PinPy folder. Please check that. Because I tried with your files and images it definitely works.

**Comment by Elddreki2** [comment]
@hevalhazalkurt  The camping section is deleted. I copied yours and it looks perfect like yours above.
The image path cannot be wrong. I grabbed it from the file explorer. Here let me show you. 
This is my image path.
`Users\horto\Desktop\PinPy\PinPy\images`
I open the file explorer, go to the same folder the Pin_copy.py is located and open that image path. I copy the root directory on the top, which is `C:\Users\horto\Desktop\PinPy\PinPy\images`, then I simply remove `C:\`.

Maybe theres something so obvious that I am missing it? Could it possibly be with the folder directory in the program since I am running Win10? The slashes I am using are \ left slashes, same as in my file explorer, but some in the program are right slashes / (I never changed any). Here's an example. 

`image_list = []
for filename in glob.glob('images/*.jpg'):`
Notice the /. Could that be messing it up? I doubt it. I'm not the programmer here lol, so I know you did nothing wrong when programming it. I am going to try running it again real fast.

**Comment by Elddreki2** [comment]
@hevalhazalkurt  Same result.
File not found : `Users\horto\Desktop\PinPy\PinPy\images01_Rush_Deer_RG10_Folding_Knife_Pocket_Knife_with_Liner_Lock_Pocketclip_Glass_Breaker_Seatbelt_Cutter_and_Perfect_for_Survival_Hiking_Camping_Fishing.jpg
  (Session info: chrome=87.0.4280.141)`
I am going to try a completely different path. I placed the images folder in the desktop.
`Users\horto\Desktop\images`

Now it works fine! Except for the fact that it pins 0 images, could that be because I already manually pinned them???? So I have absolutely no clue what to do or what's going on but oh well..

**Comment by hevalhazalkurt** [comment]
As I said I check the code and it works. Maybe you should learn a little bit the syntax of Python. Sorry.
