### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by umithyo** [hevalhazalkurt/PinPy#5]
Hello, first of all thank you for your work and for making it open source. I am getting an error when I try to run it. Possibly I'm doing something wrong. Can you help me? 

 
![unknown](https://user-images.githubusercontent.com/12802646/107079868-86c14080-6801-11eb-9e89-67f6c2c57585.png)

**Comment by hevalhazalkurt** [comment]
@umithyo It means you didn't set up your program and your image-link pairs properly. Please check the documentation and settings again.
